config/routes.rb
Rails.application.routes.draw do
  root 'breeds#index'
  post 'breeds/fetch_breed', to: 'breeds#fetch_breed', as: :fetch_breed
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  require 'net/http'

  def index
    # This action can be used to render a form for breed input or a list of breeds.
  end

  def fetch_breed
    breed = params[:breed].downcase
    url = URI("https://dog.ceo/api/breed/#{breed}/images/random")

    begin
      response = Net::HTTP.get(url)
      result = JSON.parse(response)

      if result['status'] == 'success'
        @breed_name = breed.capitalize
        @image_url = result['message']
      else
        @error = "Breed not found"
      end
    rescue JSON::ParserError => e
      @error = "Error parsing the response"
      Rails.logger.error("JSON::ParserError: #{e.message}")
    rescue StandardError => e
      @error = "An error occurred: #{e.message}"
      Rails.logger.error("StandardError: #{e.message}")
    end

    respond_to do |format|
      if @error
        format.turbo_stream { render turbo_stream: turbo_stream.replace('breed_info', partial: 'breed_result', locals: { error: @error }) }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('breed_info', partial: 'breed_result', locals: { image_url: @image_url, breed_name: @breed_name, error: @error }) }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/views/breeds/_breed_result.html.erb
<% if error %>
  <div id="breed_info">
    <p><%= error %></p>
  </div>
<% else %>
  <div id="breed_info">
    <h2><%= breed_name %></h2>
    <img src="<%= image_url %>" alt="<%= breed_name %> image">
  </div>
<% end %>

app/views/breeds/index.html.erb
<turbo-frame id="image-frame">
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <%= form_with url: fetch_breed_path, id: "breed_form", local: false do |form| %>
        <div class="input-group mb-3">
          <%= form.text_field :breed, placeholder: "Enter dog breed", class: "form-control" %>
          <div class="input-group-append">
            <%= form.submit "Submit", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <div id="breed_info"></div>
    </div>
  </div>
</div>
</turbo-frame>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogbreed</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Add Bootstrap CSS from CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRa33Zpo5j3/ZxNu3uZbs1VFAmkwq/T0ou3TsZK5F" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>